/* Generated By:JavaCC: Do not edit this line. SmartQLParserVisitor.java Version 4.1d1 */
package com.xiaomi.smartql.parser;

public interface SmartQLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=b258318cd33ba1b74f08095ea04c0175 (do not edit this line) */
